---
title: "Data"
author: "Zehua Zeng"
date: "10/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# drop NA
df <- road_traffic %>% drop_na(reportyear)
df <-df %>% drop_na(county_name)

# find year 2009 
df2009 <- df[df$reportyear == 2009,]

df_all <- df2009[df2009$mode == 'All modes',]
df_ak <- df_all[df_all$severity == 'Killed',]
df_as <- df_all[df_all$severity == 'Severe Injury',]

library(dplyr)
df_ak[, 13] <- sapply(df_ak[, 13], as.integer)
df_top <- df_ak %>% filter(injuries > 100)

library(ggplot2)
ggplot(data=df_top, aes(x=geoname, y=injuries)) +
     geom_bar(stat="identity") +
     ggtitle("the number of killed for top 9 cities in CA, 2009")

df_as[, 13] <- sapply(df_as[, 13], as.integer)
df_top <- df_as %>% filter(injuries > 300)

ggplot(data=df_top, aes(x=geoname, y=injuries)) +
     geom_bar(stat="identity") + 
     ggtitle("the number of severe injuries for top 9 cities in CA, 2009")
```


```{r}
# repeat for year 2010
df2010 <- df[df$reportyear == 2010,]

df_all <- df2010[df2010$mode == 'All modes',]
df_ak <- df_all[df_all$severity == 'Killed',]
df_as <- df_all[df_all$severity == 'Severe Injury',]

library(dplyr)
df_ak[, 13] <- sapply(df_ak[, 13], as.integer)
df_top <- df_ak %>% filter(injuries > 100)

library(ggplot2)
ggplot(data=df_top, aes(x=geoname, y=injuries)) +
     geom_bar(stat="identity") +
     ggtitle("the number of killed for top 9 cities in CA, 2010")

df_as[, 13] <- sapply(df_as[, 13], as.integer)
df_top <- df_as %>% filter(injuries > 300)

ggplot(data=df_top, aes(x=geoname, y=injuries)) +
     geom_bar(stat="identity") + 
     ggtitle("the number of severe injuries for top 9 cities in CA, 2010")
```




